### ISSUE TITLE
Implement robots shooting their own lasers when facing other robots.

### ISSUE THREAD

**Issue by felixtiller** [inf112-v21/Anisometropia#37]
Jeg ønsker at roboten min skal skyte en laser i den retningen den peker i slutten av runden.

\
_Akseptansekriterier:_
Gitt at en robot står rettet mot en annen robot:
1. Roboten jeg peker på skal ta skade av laseren min.
2. Laserene skal skytes på slutten av runden.

\
_Arbeidsoppgaver:_
- Gå igjennom for hver spiller i slutten av runden, og finn ut hvilken retning spilleren står.
- skyt en laser i gitt retning og se om det står en spiller i denne posisjonen.
- laseren min skal ikke kunne gå gjennom vegger.

**Comment by BunnyTard** [comment]
Players can now shoot lasers if they face eachother. wont shoot throught any wall tiles.
this needs to be fixed, by checking if a laser can move through.
